### ISSUE TITLE
Ping control frames never parsed

### ISSUE THREAD

**Issue by arnarg** [rawhat/mist#20]
I'm getting the following errors with a long running websocket connection.

```
=ERROR REPORT==== 7-Jun-2023::09:13:17.031402 ===
Error in process <0.123.0> with exit value:
{{case_clause,9},
 [{mist@internal@websocket,frame_from_message,3,
                           [{file,"/home/arnar/Code/gliew/build/dev/erlang/mist/_gleam_artefacts/mist@internal@websocket.erl"},
                            {line,154}]},
  {mist@internal@handler,handle_websocket_message,3,
                         [{file,"/home/arnar/Code/gliew/build/dev/erlang/mist/_gleam_artefacts/mist@internal@handler.erl"},
                          {line,28}]},
  {glisten@handler,'-start/1-fun-3-',3,
                   [{file,"/home/arnar/Code/gliew/build/dev/erlang/glisten/_gleam_artefacts/glisten@handler.erl"},
                    {line,169}]},
  {gleam@otp@actor,loop,1,
                   [{file,"/home/arnar/Code/gliew/build/dev/erlang/gleam_otp/_gleam_artefacts/gleam@otp@actor.erl"},
                    {line,137}]}]}
```

Which I have traced to https://github.com/rawhat/mist/blob/v0.11.0/src/mist/internal/websocket.gleam#L63 as it's not matching opcode 9 afaict.

[Here](https://github.com/rawhat/mist/blob/v0.11.0/src/mist/internal/handler.gleam#L118) it's expecting it as a possible output from `frame_from_message` but if I'm not mistaken this will never happen.

**Comment by rawhat** [comment]
Huh, yeah that does seem like it needs to be handled.  Just an oversight on my part, I'm sure.  I can look into that.  Thank you!

**Comment by rawhat** [comment]
This should be good now.  It did also uncover a few things I'm doing incorrectly per the RFC, but I'm going to tackle those separately.

Thanks for catching this 😄

**Comment by arnarg** [comment]
Perfect! Thanks! 🎉
