### ISSUE TITLE
Return 500 and a body when the application crashes

### ISSUE THREAD

**Issue by lpil** [rawhat/mist#4]
Hello!

Currently when the web handler crashes the connection is closed. I think we would want to instead return 500 and a body, perhaps `Internal server error`.

We would also want to ensure that the error is logged using the Erlang logger.

**Comment by rawhat** [comment]
Wrapped the call to the HTTP handler in a `gleam/erlang.{rescue}` 🎉 

Also added a super small wrapper around the `logger:error` method.  Works in the interim, until we decide on anything more robust!

**Comment by lpil** [comment]
Brill, thank you
