### ISSUE TITLE
Broken syntax highlighting inside hexdocs

### ISSUE THREAD

**Issue by dakata1337** [rawhat/mist#40]
The syntax highlighting of the [documentation](https://hexdocs.pm/mist/index.html) doesn't render properly. A rebuild of the docs fixes the issue.

![image](https://github.com/rawhat/mist/assets/61119347/8c8901a0-031d-49b5-926a-d19218f6c18c)

**Comment by rawhat** [comment]
Thank you!  The fix for this was merged into the Gleam main branch.  I'll update this in the near future.
